/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class AlarmState {
  public final static AlarmState ALARMSTATE_NONE = new AlarmState("ALARMSTATE_NONE", ElkM1APIJNI.ALARMSTATE_NONE_get());
  public final static AlarmState ALARMSTATE_ENTRANCE_DELAY = new AlarmState("ALARMSTATE_ENTRANCE_DELAY", ElkM1APIJNI.ALARMSTATE_ENTRANCE_DELAY_get());
  public final static AlarmState ALARMSTATE_ALARM_ABORT_DELAY = new AlarmState("ALARMSTATE_ALARM_ABORT_DELAY", ElkM1APIJNI.ALARMSTATE_ALARM_ABORT_DELAY_get());
  public final static AlarmState ALARMSTATE_FIRE = new AlarmState("ALARMSTATE_FIRE", ElkM1APIJNI.ALARMSTATE_FIRE_get());
  public final static AlarmState ALARMSTATE_MEDICAL = new AlarmState("ALARMSTATE_MEDICAL", ElkM1APIJNI.ALARMSTATE_MEDICAL_get());
  public final static AlarmState ALARMSTATE_POLICE = new AlarmState("ALARMSTATE_POLICE", ElkM1APIJNI.ALARMSTATE_POLICE_get());
  public final static AlarmState ALARMSTATE_BURGLAR = new AlarmState("ALARMSTATE_BURGLAR", ElkM1APIJNI.ALARMSTATE_BURGLAR_get());
  public final static AlarmState ALARMSTATE_AUX1 = new AlarmState("ALARMSTATE_AUX1", ElkM1APIJNI.ALARMSTATE_AUX1_get());
  public final static AlarmState ALARMSTATE_AUX2 = new AlarmState("ALARMSTATE_AUX2", ElkM1APIJNI.ALARMSTATE_AUX2_get());
  public final static AlarmState ALARMSTATE_AUX3 = new AlarmState("ALARMSTATE_AUX3", ElkM1APIJNI.ALARMSTATE_AUX3_get());
  public final static AlarmState ALARMSTATE_AUX4 = new AlarmState("ALARMSTATE_AUX4", ElkM1APIJNI.ALARMSTATE_AUX4_get());
  public final static AlarmState ALARMSTATE_CARBON_MONOXIDE = new AlarmState("ALARMSTATE_CARBON_MONOXIDE", ElkM1APIJNI.ALARMSTATE_CARBON_MONOXIDE_get());
  public final static AlarmState ALARMSTATE_EMERGENCY = new AlarmState("ALARMSTATE_EMERGENCY", ElkM1APIJNI.ALARMSTATE_EMERGENCY_get());
  public final static AlarmState ALARMSTATE_FREEZE = new AlarmState("ALARMSTATE_FREEZE", ElkM1APIJNI.ALARMSTATE_FREEZE_get());
  public final static AlarmState ALARMSTATE_GAS = new AlarmState("ALARMSTATE_GAS", ElkM1APIJNI.ALARMSTATE_GAS_get());
  public final static AlarmState ALARMSTATE_HEAT = new AlarmState("ALARMSTATE_HEAT", ElkM1APIJNI.ALARMSTATE_HEAT_get());
  public final static AlarmState ALARMSTATE_WATER = new AlarmState("ALARMSTATE_WATER", ElkM1APIJNI.ALARMSTATE_WATER_get());
  public final static AlarmState ALARMSTATE_FIRE_SUPERVISORY = new AlarmState("ALARMSTATE_FIRE_SUPERVISORY", ElkM1APIJNI.ALARMSTATE_FIRE_SUPERVISORY_get());
  public final static AlarmState ALARMSTATE_VERIFY_FIRE = new AlarmState("ALARMSTATE_VERIFY_FIRE", ElkM1APIJNI.ALARMSTATE_VERIFY_FIRE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AlarmState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AlarmState.class + " with value " + swigValue);
  }

  private AlarmState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AlarmState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AlarmState(String swigName, AlarmState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AlarmState[] swigValues = { ALARMSTATE_NONE, ALARMSTATE_ENTRANCE_DELAY, ALARMSTATE_ALARM_ABORT_DELAY, ALARMSTATE_FIRE, ALARMSTATE_MEDICAL, ALARMSTATE_POLICE, ALARMSTATE_BURGLAR, ALARMSTATE_AUX1, ALARMSTATE_AUX2, ALARMSTATE_AUX3, ALARMSTATE_AUX4, ALARMSTATE_CARBON_MONOXIDE, ALARMSTATE_EMERGENCY, ALARMSTATE_FREEZE, ALARMSTATE_GAS, ALARMSTATE_HEAT, ALARMSTATE_WATER, ALARMSTATE_FIRE_SUPERVISORY, ALARMSTATE_VERIFY_FIRE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

