/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class ArmMode {
  public final static ArmMode ARM_DISARMED = new ArmMode("ARM_DISARMED", ElkM1APIJNI.ARM_DISARMED_get());
  public final static ArmMode ARM_AWAY = new ArmMode("ARM_AWAY", ElkM1APIJNI.ARM_AWAY_get());
  public final static ArmMode ARM_STAY = new ArmMode("ARM_STAY", ElkM1APIJNI.ARM_STAY_get());
  public final static ArmMode ARM_STAYINSTANT = new ArmMode("ARM_STAYINSTANT", ElkM1APIJNI.ARM_STAYINSTANT_get());
  public final static ArmMode ARM_NIGHT = new ArmMode("ARM_NIGHT", ElkM1APIJNI.ARM_NIGHT_get());
  public final static ArmMode ARM_NIGHTINSTANT = new ArmMode("ARM_NIGHTINSTANT", ElkM1APIJNI.ARM_NIGHTINSTANT_get());
  public final static ArmMode ARM_VACATION = new ArmMode("ARM_VACATION", ElkM1APIJNI.ARM_VACATION_get());
  public final static ArmMode ARM_AWAYNEXT = new ArmMode("ARM_AWAYNEXT", ElkM1APIJNI.ARM_AWAYNEXT_get());
  public final static ArmMode ARM_STAYNEXT = new ArmMode("ARM_STAYNEXT", ElkM1APIJNI.ARM_STAYNEXT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ArmMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ArmMode.class + " with value " + swigValue);
  }

  private ArmMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ArmMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ArmMode(String swigName, ArmMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ArmMode[] swigValues = { ARM_DISARMED, ARM_AWAY, ARM_STAY, ARM_STAYINSTANT, ARM_NIGHT, ARM_NIGHTINSTANT, ARM_VACATION, ARM_AWAYNEXT, ARM_STAYNEXT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

