/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class ArmStatusVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArmStatusVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArmStatusVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_ArmStatusVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArmStatusVector() {
    this(ElkM1APIJNI.new_ArmStatusVector__SWIG_0(), true);
  }

  public ArmStatusVector(long n) {
    this(ElkM1APIJNI.new_ArmStatusVector__SWIG_1(n), true);
  }

  public long size() {
    return ElkM1APIJNI.ArmStatusVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ElkM1APIJNI.ArmStatusVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ElkM1APIJNI.ArmStatusVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ElkM1APIJNI.ArmStatusVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ElkM1APIJNI.ArmStatusVector_clear(swigCPtr, this);
  }

  public void add(ArmStatus x) {
    ElkM1APIJNI.ArmStatusVector_add(swigCPtr, this, ArmStatus.getCPtr(x), x);
  }

  public ArmStatus get(int i) {
    return new ArmStatus(ElkM1APIJNI.ArmStatusVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, ArmStatus val) {
    ElkM1APIJNI.ArmStatusVector_set(swigCPtr, this, i, ArmStatus.getCPtr(val), val);
  }

}
