/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class ArmStatus {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArmStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArmStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_ArmStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(ArmMode value) {
    ElkM1APIJNI.ArmStatus_mode_set(swigCPtr, this, value.swigValue());
  }

  public ArmMode getMode() {
    return ArmMode.swigToEnum(ElkM1APIJNI.ArmStatus_mode_get(swigCPtr, this));
  }

  public void setIsReady(ArmUpMode value) {
    ElkM1APIJNI.ArmStatus_isReady_set(swigCPtr, this, value.swigValue());
  }

  public ArmUpMode getIsReady() {
    return ArmUpMode.swigToEnum(ElkM1APIJNI.ArmStatus_isReady_get(swigCPtr, this));
  }

  public void setAlarm(AlarmState value) {
    ElkM1APIJNI.ArmStatus_alarm_set(swigCPtr, this, value.swigValue());
  }

  public AlarmState getAlarm() {
    return AlarmState.swigToEnum(ElkM1APIJNI.ArmStatus_alarm_get(swigCPtr, this));
  }

  public ArmStatus() {
    this(ElkM1APIJNI.new_ArmStatus(), true);
  }

}
