/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class ArmUpMode {
  public final static ArmUpMode ARMUPMODE_NOTREADY = new ArmUpMode("ARMUPMODE_NOTREADY", ElkM1APIJNI.ARMUPMODE_NOTREADY_get());
  public final static ArmUpMode ARMUPMODE_READY = new ArmUpMode("ARMUPMODE_READY", ElkM1APIJNI.ARMUPMODE_READY_get());
  public final static ArmUpMode ARMUPMODE_READYFORCE = new ArmUpMode("ARMUPMODE_READYFORCE", ElkM1APIJNI.ARMUPMODE_READYFORCE_get());
  public final static ArmUpMode ARMUPMODE_ARMEDEXITTIMER = new ArmUpMode("ARMUPMODE_ARMEDEXITTIMER", ElkM1APIJNI.ARMUPMODE_ARMEDEXITTIMER_get());
  public final static ArmUpMode ARMUPMODE_ARMED = new ArmUpMode("ARMUPMODE_ARMED", ElkM1APIJNI.ARMUPMODE_ARMED_get());
  public final static ArmUpMode ARMUPMODE_ARMEDFORCE = new ArmUpMode("ARMUPMODE_ARMEDFORCE", ElkM1APIJNI.ARMUPMODE_ARMEDFORCE_get());
  public final static ArmUpMode ARMUPMODE_ARMEDBYPASS = new ArmUpMode("ARMUPMODE_ARMEDBYPASS", ElkM1APIJNI.ARMUPMODE_ARMEDBYPASS_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ArmUpMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ArmUpMode.class + " with value " + swigValue);
  }

  private ArmUpMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ArmUpMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ArmUpMode(String swigName, ArmUpMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ArmUpMode[] swigValues = { ARMUPMODE_NOTREADY, ARMUPMODE_READY, ARMUPMODE_READYFORCE, ARMUPMODE_ARMEDEXITTIMER, ARMUPMODE_ARMED, ARMUPMODE_ARMEDFORCE, ARMUPMODE_ARMEDBYPASS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

