/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class C1M1Tunnel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected C1M1Tunnel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(C1M1Tunnel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_C1M1Tunnel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ElkM1APIJNI.C1M1Tunnel_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ElkM1APIJNI.C1M1Tunnel_change_ownership(this, swigCPtr, true);
  }

  public C1M1Tunnel(M1Connection underlying) {
    this(ElkM1APIJNI.new_C1M1Tunnel(M1Connection.getCPtr(underlying), underlying), true);
    ElkM1APIJNI.C1M1Tunnel_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public NetworkType Authenticate(String username, String password, String sernum) {
    return NetworkType.swigToEnum(ElkM1APIJNI.C1M1Tunnel_Authenticate(swigCPtr, this, username, password, sernum));
  }

  public boolean Connect(String location, int port) {
    return (getClass() == C1M1Tunnel.class) ? ElkM1APIJNI.C1M1Tunnel_Connect(swigCPtr, this, location, port) : ElkM1APIJNI.C1M1Tunnel_ConnectSwigExplicitC1M1Tunnel(swigCPtr, this, location, port);
  }

  public void Disconnect() {
    if (getClass() == C1M1Tunnel.class) ElkM1APIJNI.C1M1Tunnel_Disconnect(swigCPtr, this); else ElkM1APIJNI.C1M1Tunnel_DisconnectSwigExplicitC1M1Tunnel(swigCPtr, this);
  }

  public void Send(CharVector data) {
    if (getClass() == C1M1Tunnel.class) ElkM1APIJNI.C1M1Tunnel_Send(swigCPtr, this, CharVector.getCPtr(data), data); else ElkM1APIJNI.C1M1Tunnel_SendSwigExplicitC1M1Tunnel(swigCPtr, this, CharVector.getCPtr(data), data);
  }

  public CharVector Recieve() {
    return new CharVector((getClass() == C1M1Tunnel.class) ? ElkM1APIJNI.C1M1Tunnel_Recieve(swigCPtr, this) : ElkM1APIJNI.C1M1Tunnel_RecieveSwigExplicitC1M1Tunnel(swigCPtr, this), true);
  }

}
