/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class ChimeModeVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChimeModeVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChimeModeVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_ChimeModeVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChimeModeVector() {
    this(ElkM1APIJNI.new_ChimeModeVector__SWIG_0(), true);
  }

  public ChimeModeVector(long n) {
    this(ElkM1APIJNI.new_ChimeModeVector__SWIG_1(n), true);
  }

  public long size() {
    return ElkM1APIJNI.ChimeModeVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ElkM1APIJNI.ChimeModeVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ElkM1APIJNI.ChimeModeVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ElkM1APIJNI.ChimeModeVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ElkM1APIJNI.ChimeModeVector_clear(swigCPtr, this);
  }

  public void add(SChimeMode x) {
    ElkM1APIJNI.ChimeModeVector_add(swigCPtr, this, SChimeMode.getCPtr(x), x);
  }

  public SChimeMode get(int i) {
    return new SChimeMode(ElkM1APIJNI.ChimeModeVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SChimeMode val) {
    ElkM1APIJNI.ChimeModeVector_set(swigCPtr, this, i, SChimeMode.getCPtr(val), val);
  }

}
