/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class ChimeMode {
  public final static ChimeMode CHIMEMODE_OFF = new ChimeMode("CHIMEMODE_OFF");
  public final static ChimeMode CHIMEMODE_CHIMEONLY = new ChimeMode("CHIMEMODE_CHIMEONLY");
  public final static ChimeMode CHIMEMODE_VOICEONLY = new ChimeMode("CHIMEMODE_VOICEONLY");
  public final static ChimeMode CHIMEMODE_BOTH = new ChimeMode("CHIMEMODE_BOTH");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ChimeMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ChimeMode.class + " with value " + swigValue);
  }

  private ChimeMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ChimeMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ChimeMode(String swigName, ChimeMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ChimeMode[] swigValues = { CHIMEMODE_OFF, CHIMEMODE_CHIMEONLY, CHIMEMODE_VOICEONLY, CHIMEMODE_BOTH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

