/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class clearMethod {
  public final static clearMethod CLEAR = new clearMethod("CLEAR", ElkM1APIJNI.CLEAR_get());
  public final static clearMethod CLEAR_WITH_STAR = new clearMethod("CLEAR_WITH_STAR", ElkM1APIJNI.CLEAR_WITH_STAR_get());
  public final static clearMethod CLEAR_DISPLAY_UNTIL_TIMEOUT = new clearMethod("CLEAR_DISPLAY_UNTIL_TIMEOUT", ElkM1APIJNI.CLEAR_DISPLAY_UNTIL_TIMEOUT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static clearMethod swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + clearMethod.class + " with value " + swigValue);
  }

  private clearMethod(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private clearMethod(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private clearMethod(String swigName, clearMethod swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static clearMethod[] swigValues = { CLEAR, CLEAR_WITH_STAR, CLEAR_DISPLAY_UNTIL_TIMEOUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

