/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class FKEY {
  public final static FKEY FKEY_1 = new FKEY("FKEY_1");
  public final static FKEY FKEY_2 = new FKEY("FKEY_2");
  public final static FKEY FKEY_3 = new FKEY("FKEY_3");
  public final static FKEY FKEY_4 = new FKEY("FKEY_4");
  public final static FKEY FKEY_5 = new FKEY("FKEY_5");
  public final static FKEY FKEY_6 = new FKEY("FKEY_6");
  public final static FKEY FKEY_STAR = new FKEY("FKEY_STAR");
  public final static FKEY FKEY_CHIME = new FKEY("FKEY_CHIME");
  public final static FKEY FKEY_NONE = new FKEY("FKEY_NONE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FKEY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FKEY.class + " with value " + swigValue);
  }

  private FKEY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FKEY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FKEY(String swigName, FKEY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FKEY[] swigValues = { FKEY_1, FKEY_2, FKEY_3, FKEY_4, FKEY_5, FKEY_6, FKEY_STAR, FKEY_CHIME, FKEY_NONE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

