/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class IntCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_IntCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ElkM1APIJNI.IntCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ElkM1APIJNI.IntCallback_change_ownership(this, swigCPtr, true);
  }

  public void run(int arg1) {
    ElkM1APIJNI.IntCallback_run(swigCPtr, this, arg1);
  }

  public IntCallback() {
    this(ElkM1APIJNI.new_IntCallback(), true);
    ElkM1APIJNI.IntCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
