/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class LogEntryVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LogEntryVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogEntryVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_LogEntryVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LogEntryVector() {
    this(ElkM1APIJNI.new_LogEntryVector__SWIG_0(), true);
  }

  public LogEntryVector(long n) {
    this(ElkM1APIJNI.new_LogEntryVector__SWIG_1(n), true);
  }

  public long size() {
    return ElkM1APIJNI.LogEntryVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ElkM1APIJNI.LogEntryVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ElkM1APIJNI.LogEntryVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ElkM1APIJNI.LogEntryVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ElkM1APIJNI.LogEntryVector_clear(swigCPtr, this);
  }

  public void add(LogEntry x) {
    ElkM1APIJNI.LogEntryVector_add(swigCPtr, this, LogEntry.getCPtr(x), x);
  }

  public LogEntry get(int i) {
    return new LogEntry(ElkM1APIJNI.LogEntryVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, LogEntry val) {
    ElkM1APIJNI.LogEntryVector_set(swigCPtr, this, i, LogEntry.getCPtr(val), val);
  }

}
