/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class LogEntry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LogEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_LogEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEvent(int value) {
    ElkM1APIJNI.LogEntry_event_set(swigCPtr, this, value);
  }

  public int getEvent() {
    return ElkM1APIJNI.LogEntry_event_get(swigCPtr, this);
  }

  public void setEventSubjectNumber(int value) {
    ElkM1APIJNI.LogEntry_eventSubjectNumber_set(swigCPtr, this, value);
  }

  public int getEventSubjectNumber() {
    return ElkM1APIJNI.LogEntry_eventSubjectNumber_get(swigCPtr, this);
  }

  public void setArea(int value) {
    ElkM1APIJNI.LogEntry_area_set(swigCPtr, this, value);
  }

  public int getArea() {
    return ElkM1APIJNI.LogEntry_area_get(swigCPtr, this);
  }

  public void setHour(int value) {
    ElkM1APIJNI.LogEntry_hour_set(swigCPtr, this, value);
  }

  public int getHour() {
    return ElkM1APIJNI.LogEntry_hour_get(swigCPtr, this);
  }

  public void setMinute(int value) {
    ElkM1APIJNI.LogEntry_minute_set(swigCPtr, this, value);
  }

  public int getMinute() {
    return ElkM1APIJNI.LogEntry_minute_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    ElkM1APIJNI.LogEntry_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return ElkM1APIJNI.LogEntry_month_get(swigCPtr, this);
  }

  public void setDay(int value) {
    ElkM1APIJNI.LogEntry_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return ElkM1APIJNI.LogEntry_day_get(swigCPtr, this);
  }

  public void setIndex(int value) {
    ElkM1APIJNI.LogEntry_index_set(swigCPtr, this, value);
  }

  public int getIndex() {
    return ElkM1APIJNI.LogEntry_index_get(swigCPtr, this);
  }

  public void setYear(int value) {
    ElkM1APIJNI.LogEntry_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return ElkM1APIJNI.LogEntry_year_get(swigCPtr, this);
  }

  public void setDayOfWeek(Weekday value) {
    ElkM1APIJNI.LogEntry_dayOfWeek_set(swigCPtr, this, value.swigValue());
  }

  public Weekday getDayOfWeek() {
    return Weekday.swigToEnum(ElkM1APIJNI.LogEntry_dayOfWeek_get(swigCPtr, this));
  }

  public LogEntry() {
    this(ElkM1APIJNI.new_LogEntry(), true);
  }

}
