/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class LogicalZoneState {
  public final static LogicalZoneState LZS_NORMAL = new LogicalZoneState("LZS_NORMAL");
  public final static LogicalZoneState LZS_TROUBLE = new LogicalZoneState("LZS_TROUBLE");
  public final static LogicalZoneState LZS_VIOLATED = new LogicalZoneState("LZS_VIOLATED");
  public final static LogicalZoneState LZS_BYPASSED = new LogicalZoneState("LZS_BYPASSED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LogicalZoneState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LogicalZoneState.class + " with value " + swigValue);
  }

  private LogicalZoneState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LogicalZoneState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LogicalZoneState(String swigName, LogicalZoneState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LogicalZoneState[] swigValues = { LZS_NORMAL, LZS_TROUBLE, LZS_VIOLATED, LZS_BYPASSED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

