/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class M1AsciiAPI extends M1Monitor {
  private transient long swigCPtr;

  protected M1AsciiAPI(long cPtr, boolean cMemoryOwn) {
    super(ElkM1APIJNI.M1AsciiAPI_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(M1AsciiAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_M1AsciiAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public M1AsciiAPI(M1Connection conn) {
    this(ElkM1APIJNI.new_M1AsciiAPI(M1Connection.getCPtr(conn), conn), true);
  }

  public void collectNames(TextDescriptionType type) {
    ElkM1APIJNI.M1AsciiAPI_collectNames(swigCPtr, this, type.swigValue());
  }

  public IntVector getConfiguredAreas() {
    return new IntVector(ElkM1APIJNI.M1AsciiAPI_getConfiguredAreas(swigCPtr, this), true);
  }

  public void displayLCDText(int area, clearMethod clear, boolean beepKeypad, int displayTime, String text) {
    ElkM1APIJNI.M1AsciiAPI_displayLCDText__SWIG_0(swigCPtr, this, area, clear.swigValue(), beepKeypad, displayTime, text);
  }

  public void displayLCDText(int area, clearMethod clear, boolean beepKeypad, int displayTime, String lineOne, String lineTwo) {
    ElkM1APIJNI.M1AsciiAPI_displayLCDText__SWIG_1(swigCPtr, this, area, clear.swigValue(), beepKeypad, displayTime, lineOne, lineTwo);
  }

}
