/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class M1Connection {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected M1Connection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(M1Connection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_M1Connection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ElkM1APIJNI.M1Connection_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ElkM1APIJNI.M1Connection_change_ownership(this, swigCPtr, true);
  }

  public boolean Connect(String location, int port) {
    return ElkM1APIJNI.M1Connection_Connect(swigCPtr, this, location, port);
  }

  public void Disconnect() {
    ElkM1APIJNI.M1Connection_Disconnect(swigCPtr, this);
  }

  public void Send(CharVector data) {
    ElkM1APIJNI.M1Connection_Send(swigCPtr, this, CharVector.getCPtr(data), data);
  }

  public CharVector Recieve() {
    return new CharVector(ElkM1APIJNI.M1Connection_Recieve(swigCPtr, this), true);
  }

  public M1Connection() {
    this(ElkM1APIJNI.new_M1Connection(), true);
    ElkM1APIJNI.M1Connection_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
