/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class M1Monitor extends M1API {
  private transient long swigCPtr;

  protected M1Monitor(long cPtr, boolean cMemoryOwn) {
    super(ElkM1APIJNI.M1Monitor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(M1Monitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_M1Monitor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void run() {
    ElkM1APIJNI.M1Monitor_run(swigCPtr, this);
  }

  public void stop() {
    ElkM1APIJNI.M1Monitor_stop(swigCPtr, this);
  }

}
