/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class RTCData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RTCData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RTCData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_RTCData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSeconds(int value) {
    ElkM1APIJNI.RTCData_seconds_set(swigCPtr, this, value);
  }

  public int getSeconds() {
    return ElkM1APIJNI.RTCData_seconds_get(swigCPtr, this);
  }

  public void setMinutes(int value) {
    ElkM1APIJNI.RTCData_minutes_set(swigCPtr, this, value);
  }

  public int getMinutes() {
    return ElkM1APIJNI.RTCData_minutes_get(swigCPtr, this);
  }

  public void setHours(int value) {
    ElkM1APIJNI.RTCData_hours_set(swigCPtr, this, value);
  }

  public int getHours() {
    return ElkM1APIJNI.RTCData_hours_get(swigCPtr, this);
  }

  public void setWeekday(Weekday value) {
    ElkM1APIJNI.RTCData_weekday_set(swigCPtr, this, value.swigValue());
  }

  public Weekday getWeekday() {
    return Weekday.swigToEnum(ElkM1APIJNI.RTCData_weekday_get(swigCPtr, this));
  }

  public void setDay(int value) {
    ElkM1APIJNI.RTCData_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return ElkM1APIJNI.RTCData_day_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    ElkM1APIJNI.RTCData_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return ElkM1APIJNI.RTCData_month_get(swigCPtr, this);
  }

  public void setYear(int value) {
    ElkM1APIJNI.RTCData_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return ElkM1APIJNI.RTCData_year_get(swigCPtr, this);
  }

  public void setTwelveHourClock(boolean value) {
    ElkM1APIJNI.RTCData_twelveHourClock_set(swigCPtr, this, value);
  }

  public boolean getTwelveHourClock() {
    return ElkM1APIJNI.RTCData_twelveHourClock_get(swigCPtr, this);
  }

  public void setDayBeforeMonth(boolean value) {
    ElkM1APIJNI.RTCData_dayBeforeMonth_set(swigCPtr, this, value);
  }

  public boolean getDayBeforeMonth() {
    return ElkM1APIJNI.RTCData_dayBeforeMonth_get(swigCPtr, this);
  }

  public RTCData() {
    this(ElkM1APIJNI.new_RTCData(), true);
  }

}
