/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class SChimeMode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SChimeMode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SChimeMode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_SChimeMode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCm(ChimeMode value) {
    ElkM1APIJNI.SChimeMode_cm_set(swigCPtr, this, value.swigValue());
  }

  public ChimeMode getCm() {
    return ChimeMode.swigToEnum(ElkM1APIJNI.SChimeMode_cm_get(swigCPtr, this));
  }

  public SChimeMode() {
    this(ElkM1APIJNI.new_SChimeMode(), true);
  }

}
