/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class TempDevicePairVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TempDevicePairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TempDevicePairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_TempDevicePairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TempDevicePairVector() {
    this(ElkM1APIJNI.new_TempDevicePairVector__SWIG_0(), true);
  }

  public TempDevicePairVector(long n) {
    this(ElkM1APIJNI.new_TempDevicePairVector__SWIG_1(n), true);
  }

  public long size() {
    return ElkM1APIJNI.TempDevicePairVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ElkM1APIJNI.TempDevicePairVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ElkM1APIJNI.TempDevicePairVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ElkM1APIJNI.TempDevicePairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ElkM1APIJNI.TempDevicePairVector_clear(swigCPtr, this);
  }

  public void add(TempDevicePair x) {
    ElkM1APIJNI.TempDevicePairVector_add(swigCPtr, this, TempDevicePair.getCPtr(x), x);
  }

  public TempDevicePair get(int i) {
    return new TempDevicePair(ElkM1APIJNI.TempDevicePairVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, TempDevicePair val) {
    ElkM1APIJNI.TempDevicePairVector_set(swigCPtr, this, i, TempDevicePair.getCPtr(val), val);
  }

}
