/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class TemperatureDevice {
  public final static TemperatureDevice TEMPDEVICE_ZONE = new TemperatureDevice("TEMPDEVICE_ZONE", ElkM1APIJNI.TEMPDEVICE_ZONE_get());
  public final static TemperatureDevice TEMPDEVICE_KEYPAD = new TemperatureDevice("TEMPDEVICE_KEYPAD", ElkM1APIJNI.TEMPDEVICE_KEYPAD_get());
  public final static TemperatureDevice TEMPDEVICE_THERMOSTAT = new TemperatureDevice("TEMPDEVICE_THERMOSTAT", ElkM1APIJNI.TEMPDEVICE_THERMOSTAT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TemperatureDevice swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TemperatureDevice.class + " with value " + swigValue);
  }

  private TemperatureDevice(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TemperatureDevice(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TemperatureDevice(String swigName, TemperatureDevice swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TemperatureDevice[] swigValues = { TEMPDEVICE_ZONE, TEMPDEVICE_KEYPAD, TEMPDEVICE_THERMOSTAT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

