/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class TextDescriptionType {
  public final static TextDescriptionType TEXT_ZoneName = new TextDescriptionType("TEXT_ZoneName");
  public final static TextDescriptionType TEXT_AreaName = new TextDescriptionType("TEXT_AreaName");
  public final static TextDescriptionType TEXT_UserName = new TextDescriptionType("TEXT_UserName");
  public final static TextDescriptionType TEXT_KeypadName = new TextDescriptionType("TEXT_KeypadName");
  public final static TextDescriptionType TEXT_OutputName = new TextDescriptionType("TEXT_OutputName");
  public final static TextDescriptionType TEXT_TaskName = new TextDescriptionType("TEXT_TaskName");
  public final static TextDescriptionType TEXT_TelephoneName = new TextDescriptionType("TEXT_TelephoneName");
  public final static TextDescriptionType TEXT_LightName = new TextDescriptionType("TEXT_LightName");
  public final static TextDescriptionType TEXT_AlarmDurationName = new TextDescriptionType("TEXT_AlarmDurationName");
  public final static TextDescriptionType TEXT_CustomSettings = new TextDescriptionType("TEXT_CustomSettings");
  public final static TextDescriptionType TEXT_CounterName = new TextDescriptionType("TEXT_CounterName");
  public final static TextDescriptionType TEXT_ThermostatName = new TextDescriptionType("TEXT_ThermostatName");
  public final static TextDescriptionType TEXT_FKEY1 = new TextDescriptionType("TEXT_FKEY1");
  public final static TextDescriptionType TEXT_FKEY2 = new TextDescriptionType("TEXT_FKEY2");
  public final static TextDescriptionType TEXT_FKEY3 = new TextDescriptionType("TEXT_FKEY3");
  public final static TextDescriptionType TEXT_FKEY4 = new TextDescriptionType("TEXT_FKEY4");
  public final static TextDescriptionType TEXT_FKEY5 = new TextDescriptionType("TEXT_FKEY5");
  public final static TextDescriptionType TEXT_FKEY6 = new TextDescriptionType("TEXT_FKEY6");
  public final static TextDescriptionType TEXT_AudioZoneName = new TextDescriptionType("TEXT_AudioZoneName");
  public final static TextDescriptionType TEXT_AudioSourceName = new TextDescriptionType("TEXT_AudioSourceName");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextDescriptionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextDescriptionType.class + " with value " + swigValue);
  }

  private TextDescriptionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextDescriptionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextDescriptionType(String swigName, TextDescriptionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextDescriptionType[] swigValues = { TEXT_ZoneName, TEXT_AreaName, TEXT_UserName, TEXT_KeypadName, TEXT_OutputName, TEXT_TaskName, TEXT_TelephoneName, TEXT_LightName, TEXT_AlarmDurationName, TEXT_CustomSettings, TEXT_CounterName, TEXT_ThermostatName, TEXT_FKEY1, TEXT_FKEY2, TEXT_FKEY3, TEXT_FKEY4, TEXT_FKEY5, TEXT_FKEY6, TEXT_AudioZoneName, TEXT_AudioSourceName };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

