/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class UserCodeSuccess {
  public final static UserCodeSuccess USERCODE_CHANGE_SUCCESSFUL = new UserCodeSuccess("USERCODE_CHANGE_SUCCESSFUL");
  public final static UserCodeSuccess USERCODE_USER_DUPLICATE = new UserCodeSuccess("USERCODE_USER_DUPLICATE");
  public final static UserCodeSuccess USERCODE_UNAUTHORIZED = new UserCodeSuccess("USERCODE_UNAUTHORIZED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static UserCodeSuccess swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + UserCodeSuccess.class + " with value " + swigValue);
  }

  private UserCodeSuccess(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private UserCodeSuccess(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private UserCodeSuccess(String swigName, UserCodeSuccess swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static UserCodeSuccess[] swigValues = { USERCODE_CHANGE_SUCCESSFUL, USERCODE_USER_DUPLICATE, USERCODE_UNAUTHORIZED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

