/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class ZoneState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZoneState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZoneState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_ZoneState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPhysicalState(PhysicalZoneState value) {
    ElkM1APIJNI.ZoneState_physicalState_set(swigCPtr, this, value.swigValue());
  }

  public PhysicalZoneState getPhysicalState() {
    return PhysicalZoneState.swigToEnum(ElkM1APIJNI.ZoneState_physicalState_get(swigCPtr, this));
  }

  public void setLogicalState(LogicalZoneState value) {
    ElkM1APIJNI.ZoneState_logicalState_set(swigCPtr, this, value.swigValue());
  }

  public LogicalZoneState getLogicalState() {
    return LogicalZoneState.swigToEnum(ElkM1APIJNI.ZoneState_logicalState_get(swigCPtr, this));
  }

  public ZoneState() {
    this(ElkM1APIJNI.new_ZoneState(), true);
  }

}
