/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class ZoneStateVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZoneStateVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZoneStateVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_ZoneStateVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ZoneStateVector() {
    this(ElkM1APIJNI.new_ZoneStateVector__SWIG_0(), true);
  }

  public ZoneStateVector(long n) {
    this(ElkM1APIJNI.new_ZoneStateVector__SWIG_1(n), true);
  }

  public long size() {
    return ElkM1APIJNI.ZoneStateVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ElkM1APIJNI.ZoneStateVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ElkM1APIJNI.ZoneStateVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ElkM1APIJNI.ZoneStateVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ElkM1APIJNI.ZoneStateVector_clear(swigCPtr, this);
  }

  public void add(ZoneState x) {
    ElkM1APIJNI.ZoneStateVector_add(swigCPtr, this, ZoneState.getCPtr(x), x);
  }

  public ZoneState get(int i) {
    return new ZoneState(ElkM1APIJNI.ZoneStateVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, ZoneState val) {
    ElkM1APIJNI.ZoneStateVector_set(swigCPtr, this, i, ZoneState.getCPtr(val), val);
  }

}
