/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public final class ZoneDefinition {
  public final static ZoneDefinition ZONEDEF_DISABLED = new ZoneDefinition("ZONEDEF_DISABLED", ElkM1APIJNI.ZONEDEF_DISABLED_get());
  public final static ZoneDefinition ZONEDEF_BURGLAR_ENTRY_1 = new ZoneDefinition("ZONEDEF_BURGLAR_ENTRY_1", ElkM1APIJNI.ZONEDEF_BURGLAR_ENTRY_1_get());
  public final static ZoneDefinition ZONEDEF_BURGLAR_ENTRY_2 = new ZoneDefinition("ZONEDEF_BURGLAR_ENTRY_2", ElkM1APIJNI.ZONEDEF_BURGLAR_ENTRY_2_get());
  public final static ZoneDefinition ZONEDEF_BURGLAR_PERIMETER_INSTANT = new ZoneDefinition("ZONEDEF_BURGLAR_PERIMETER_INSTANT");
  public final static ZoneDefinition ZONEDEF_BURGLAR_INTERIOR = new ZoneDefinition("ZONEDEF_BURGLAR_INTERIOR");
  public final static ZoneDefinition ZONEDEF_BURGLAR_INTERIOR_FOLLOWER = new ZoneDefinition("ZONEDEF_BURGLAR_INTERIOR_FOLLOWER");
  public final static ZoneDefinition ZONEDEF_BURGLAR_INTERIOR_NIGHT = new ZoneDefinition("ZONEDEF_BURGLAR_INTERIOR_NIGHT");
  public final static ZoneDefinition ZONEDEF_BURGLAR_INTERIOR_NIGHT_DELAY = new ZoneDefinition("ZONEDEF_BURGLAR_INTERIOR_NIGHT_DELAY");
  public final static ZoneDefinition ZONEDEF_BURGLAR_24_HOUR = new ZoneDefinition("ZONEDEF_BURGLAR_24_HOUR");
  public final static ZoneDefinition ZONEDEF_BURGLAR_BOX_TAMPER = new ZoneDefinition("ZONEDEF_BURGLAR_BOX_TAMPER");
  public final static ZoneDefinition ZONEDEF_FIRE_ALARM = new ZoneDefinition("ZONEDEF_FIRE_ALARM");
  public final static ZoneDefinition ZONEDEF_FIRE_VERIFIED = new ZoneDefinition("ZONEDEF_FIRE_VERIFIED");
  public final static ZoneDefinition ZONEDEF_FIRE_SUPERVISORY = new ZoneDefinition("ZONEDEF_FIRE_SUPERVISORY");
  public final static ZoneDefinition ZONEDEF_AUX_ALARM_1 = new ZoneDefinition("ZONEDEF_AUX_ALARM_1");
  public final static ZoneDefinition ZONEDEF_AUX_ALARM_2 = new ZoneDefinition("ZONEDEF_AUX_ALARM_2");
  public final static ZoneDefinition ZONEDEF_KEY_FOB = new ZoneDefinition("ZONEDEF_KEY_FOB");
  public final static ZoneDefinition ZONEDEF_NON_ALARM = new ZoneDefinition("ZONEDEF_NON_ALARM");
  public final static ZoneDefinition ZONEDEF_CARBON_MONOXIDE = new ZoneDefinition("ZONEDEF_CARBON_MONOXIDE");
  public final static ZoneDefinition ZONEDEF_EMERGENCY_ALARM = new ZoneDefinition("ZONEDEF_EMERGENCY_ALARM");
  public final static ZoneDefinition ZONEDEF_FREEZE_ALARM = new ZoneDefinition("ZONEDEF_FREEZE_ALARM");
  public final static ZoneDefinition ZONEDEF_GAS_ALARM = new ZoneDefinition("ZONEDEF_GAS_ALARM");
  public final static ZoneDefinition ZONEDEF_HEAT_ALARM = new ZoneDefinition("ZONEDEF_HEAT_ALARM");
  public final static ZoneDefinition ZONEDEF_MEDICAL_ALARM = new ZoneDefinition("ZONEDEF_MEDICAL_ALARM");
  public final static ZoneDefinition ZONEDEF_POLICE_ALARM = new ZoneDefinition("ZONEDEF_POLICE_ALARM");
  public final static ZoneDefinition ZONEDEF_POLICE_NO_INDICATION = new ZoneDefinition("ZONEDEF_POLICE_NO_INDICATION");
  public final static ZoneDefinition ZONEDEF_WATER_ALARM = new ZoneDefinition("ZONEDEF_WATER_ALARM");
  public final static ZoneDefinition ZONEDEF_KEY_MOMENTARY_ARMDISARM = new ZoneDefinition("ZONEDEF_KEY_MOMENTARY_ARMDISARM");
  public final static ZoneDefinition ZONEDEF_KEY_MOMENTARY_ARM_AWAY = new ZoneDefinition("ZONEDEF_KEY_MOMENTARY_ARM_AWAY");
  public final static ZoneDefinition ZONEDEF_KEY_MOMENTARY_ARM_STAY = new ZoneDefinition("ZONEDEF_KEY_MOMENTARY_ARM_STAY");
  public final static ZoneDefinition ZONEDEF_KEY_MOMENTARY_DISARM = new ZoneDefinition("ZONEDEF_KEY_MOMENTARY_DISARM");
  public final static ZoneDefinition ZONEDEF_KEY_TOGGLE = new ZoneDefinition("ZONEDEF_KEY_TOGGLE");
  public final static ZoneDefinition ZONEDEF_MUTE_AUDIBLES = new ZoneDefinition("ZONEDEF_MUTE_AUDIBLES");
  public final static ZoneDefinition ZONEDEF_POWER_SUPERVISORY = new ZoneDefinition("ZONEDEF_POWER_SUPERVISORY");
  public final static ZoneDefinition ZONEDEF_TEMPERATURE = new ZoneDefinition("ZONEDEF_TEMPERATURE");
  public final static ZoneDefinition ZONEDEF_ANALOG_ZONE = new ZoneDefinition("ZONEDEF_ANALOG_ZONE");
  public final static ZoneDefinition ZONEDEF_PHONE_KEY = new ZoneDefinition("ZONEDEF_PHONE_KEY");
  public final static ZoneDefinition ZONEDEF_INTERCOM_KEY = new ZoneDefinition("ZONEDEF_INTERCOM_KEY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ZoneDefinition swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ZoneDefinition.class + " with value " + swigValue);
  }

  private ZoneDefinition(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ZoneDefinition(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ZoneDefinition(String swigName, ZoneDefinition swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ZoneDefinition[] swigValues = { ZONEDEF_DISABLED, ZONEDEF_BURGLAR_ENTRY_1, ZONEDEF_BURGLAR_ENTRY_2, ZONEDEF_BURGLAR_PERIMETER_INSTANT, ZONEDEF_BURGLAR_INTERIOR, ZONEDEF_BURGLAR_INTERIOR_FOLLOWER, ZONEDEF_BURGLAR_INTERIOR_NIGHT, ZONEDEF_BURGLAR_INTERIOR_NIGHT_DELAY, ZONEDEF_BURGLAR_24_HOUR, ZONEDEF_BURGLAR_BOX_TAMPER, ZONEDEF_FIRE_ALARM, ZONEDEF_FIRE_VERIFIED, ZONEDEF_FIRE_SUPERVISORY, ZONEDEF_AUX_ALARM_1, ZONEDEF_AUX_ALARM_2, ZONEDEF_KEY_FOB, ZONEDEF_NON_ALARM, ZONEDEF_CARBON_MONOXIDE, ZONEDEF_EMERGENCY_ALARM, ZONEDEF_FREEZE_ALARM, ZONEDEF_GAS_ALARM, ZONEDEF_HEAT_ALARM, ZONEDEF_MEDICAL_ALARM, ZONEDEF_POLICE_ALARM, ZONEDEF_POLICE_NO_INDICATION, ZONEDEF_WATER_ALARM, ZONEDEF_KEY_MOMENTARY_ARMDISARM, ZONEDEF_KEY_MOMENTARY_ARM_AWAY, ZONEDEF_KEY_MOMENTARY_ARM_STAY, ZONEDEF_KEY_MOMENTARY_DISARM, ZONEDEF_KEY_TOGGLE, ZONEDEF_MUTE_AUDIBLES, ZONEDEF_POWER_SUPERVISORY, ZONEDEF_TEMPERATURE, ZONEDEF_ANALOG_ZONE, ZONEDEF_PHONE_KEY, ZONEDEF_INTERCOM_KEY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

