/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package elkm1api;

public class ZoneDefinitionVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ZoneDefinitionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZoneDefinitionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ElkM1APIJNI.delete_ZoneDefinitionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ZoneDefinitionVector() {
    this(ElkM1APIJNI.new_ZoneDefinitionVector__SWIG_0(), true);
  }

  public ZoneDefinitionVector(long n) {
    this(ElkM1APIJNI.new_ZoneDefinitionVector__SWIG_1(n), true);
  }

  public long size() {
    return ElkM1APIJNI.ZoneDefinitionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return ElkM1APIJNI.ZoneDefinitionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ElkM1APIJNI.ZoneDefinitionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ElkM1APIJNI.ZoneDefinitionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ElkM1APIJNI.ZoneDefinitionVector_clear(swigCPtr, this);
  }

  public void add(SZoneDefinition x) {
    ElkM1APIJNI.ZoneDefinitionVector_add(swigCPtr, this, SZoneDefinition.getCPtr(x), x);
  }

  public SZoneDefinition get(int i) {
    return new SZoneDefinition(ElkM1APIJNI.ZoneDefinitionVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, SZoneDefinition val) {
    ElkM1APIJNI.ZoneDefinitionVector_set(swigCPtr, this, i, SZoneDefinition.getCPtr(val), val);
  }

}
